### ISSUE TITLE
接続事業者向けのバッチ動作確認について

### ISSUE THREAD

**Issue by sis-rionauehara** [Personal-Data-Linkage-Module/docs#23]
「接続事業者向けセミナー_STEP2-2手順詳細.xlsx」の手順番号S22-1-7を実行した際、利用者作成バッチ(create-user-batch)について正常に処理できたか確認したいです。確認方法をご教示いただけないでしょうか。
同様に、「接続事業者向けセミナー_STEP3-2手順詳細.xlsx」の手順番号S32-1-2についてもCToken連携バッチ(link-ctoken-batch)が正常に処理できたか確認したいです。確認先や確認結果サンプル等ありましたらご教授いただけると幸いです。

またパーソナルデータ連携モジュール_セミナー資料（接続事業者様向け）では、残りの12個のバッチがどの手順で必要か明記されていませんが、どのタイミングで必要になるのでしょうか。

**Comment by r-saito-cw** [comment]
@rio-uhr 
バッチ処理については、結果的にはAPI呼び出しているのみであるため、利用者作成バッチであれば内包して呼び出しているAPIの処理が完了しているかを確認するという方法になります。個別の呼び出しAPIは該当するバッチのソースコードや実行時のリクエスト・レスポンスをご確認ください。
 
利用者作成バッチは利用者が作成されているかで確認が可能です。実際にその利用者でAPI実行してみることで確認することができます。book-operateの利用者一覧検索APIの実行でも確認が可能です。利用者が作成されていなければエラーが返ってきます。
CToken連携バッチは、ctoken-ledgerのCToken取得APIの実行で確認可能です。バッチが動作していれば、蓄積したデータがこのAPIで返ってきます。
 
パーソナルデータ連携モジュールのGitHubで公開しているバッチはシステムのサンプルとして例示したものであるため、詳細なドキュメントはございません。周期や連続性、タイミングについては、個々のシステムの設計によります。
 
開発過程での成果物などで共有できるものがあれば、貢献としてご協力いただけますと大変ありがたく存じます。

回答後、一週間でCLOSEとします。

**Comment by r-saito-cw** [comment]
一週間以上経過しましたので、いったんCLOSEとします。リオープンの希望などあれば追加コメントをお願いします。
