### ISSUE TITLE
CloudSearchの使用用途について

### ISSUE THREAD

**Issue by sis-rionauehara** [Personal-Data-Linkage-Module/docs#24]
提供されているパーソナルデータ連携モジュール_セミナ－資料（構築事業者様向け）を使用して環境構築をしています。
セミナー資料内のSTEP2にてCloudSearchを構築していますが、使用用途が記載されておりません。
通常、パーソナルモジュールを運用する上で、CloudSearchの使用用途をご教授いただけないでしょうか。

**Comment by r-saito-cw** [comment]
@rio-uhr さん、docsの下だったためissueに気が付くのが遅くなりすみませんでした。

CloudSearchは主にカタログ検索機能の部分に利用されます。固有の設定を行うことで、カタログ情報の検索を効率的に実行することが可能となります。本OSSでは、サービスに依存している部分はすべてスタブ化（簡略化した実装）されています。AWS以外を採用している場合、CloudSearchの代わりに他の検索エンジンを利用することも可能となります。

利用者の方々には開発貢献としてコミュニティメンバとして加わっていただきたいのですがいかがでしょうか。特に費用などはございませんし、会社所属などはお伺いすることがあるかもしれませんが、参加資格も設けておりません。Code for Japanさんを中心として、隔週でZoomの会合を開催しておりますので、よろしければそちらもご案内します。

**Comment by r-saito-cw** [comment]
一週間以上経過しましたので、いったんCLOSEとします。リオープンの希望などあれば追加コメントをお願いします。
